version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "50954:8888"
    volumes:
      - ./backend:/app
      - db_data:/data/db
    depends_on:
      - db
    environment:
      - PORT=8888

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "59208:3333"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    environment:
      - PORT=3333

  db:
    image: sqlite
    volumes:
      - db_data:/data/db
    restart: always

  test:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: pytest tests/
    volumes:
      - ./backend:/app
      - ./tests:/tests
    depends_on:
      - db

volumes:
  db_data: