version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "52033:8888"
    volumes:
      - ./backend:/app
      - db_data:/data/db
    depends_on:
      - db
    environment:
      - PORT=8888
      - DATABASE_URL=/data/db/sql_app.db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "57851:3333"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    environment:
      - PORT=3333
      - NEXT_PUBLIC_API_URL=http://localhost:52033

  db:
    image: sqlite
    volumes:
      - db_data:/data/db
    restart: always

  test:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: pytest tests/
    volumes:
      - ./backend:/app
      - ./tests:/tests
    depends_on:
      - db

volumes:
  db_data: