version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "52802:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=sqlite:///./test.db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "56686:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  test:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: pytest tests/
    volumes:
      - ./backend:/app
      - ./tests:/tests
    environment:
      - DATABASE_URL=sqlite:///./test.db