app = "deplytestopenhands"
primary_region = "nrt"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]


[build]
  dockerfile = "Dockerfile"
  ignorefile = ".dockerignore"

[[services]]
  internal_port = 80
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1


  protocol = "tcp"
  script_checks = []