app = "your-app-name"
primary_region = "iad"

[build]
  [build.args]
    BUILDKIT_INLINE_CACHE = "1"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0