app = "your-app-name"
primary_region = "hnd"  # 東京リージョン

[build]
  builder = "paketobuildpacks/builder:base"

[http_service]
  internal_port = 59175  # フロントエンドポート
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[[services]]
  http_checks = []
  internal_port = 54935  # バックエンドポート
  protocol = "tcp"
  script_checks = []