# fly.toml app configuration file generated for fullstack-app-1747717718 on 2025-05-20T05:18:53Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fullstack-app-1747717718'
primary_region = 'hkg'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
